name: snapsheetapp
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  modal_progress_hud: ^0.1.3
  camera:
  path_provider:
  path:
  flutter_simple_calculator: ^1.0.2
  provider: ^4.1.2
  firebase_ml_vision: ^0.9.4
  image_picker: ^0.6.7
  auto_size_text: ^2.1.0
  font_awesome_flutter: ^8.8.1
  string_similarity: ^1.0.1
  intl: ^0.16.1
  sorted_list: ^0.1.0
  charts_flutter: ^0.9.0
  random_color: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/